name: xSignIn
main: de.mark615.xsignin.XSignIn
version: 1.0.6
description: Login Plugin
author: Mark615

commands:
  xsignin:
    description: xSignin command
    usage: /xsignin
    aliases: [xs, xl, xlogin]
    default: op
  agb:
    description: xAGB command
    usage: /agb
    aliases: [xagb]
    default: op
  maintenance:
    description: maintenance command
    usage: /maintenance
    aliases: [xmt, mt, xmaintenance]
    default: op
  whitelist:
    description: whitelist command
    usage: /whitelist
    aliases: [wlist]
    default: op
  blacklist:
    description: blacklist command
    usage: /blacklist
    aliases: [blist]
    default: op
permissions: