name: xSignIn
main: de.mark615.xsignin.XSignIn
version: 1.0.1
description: Login Plugin
author: Mark615

commands:
  xlogin:
    description: xSignin command
    usage: /xsignin
    aliases: [xs]
    default: op
permissions: