name: xSignIn
main: de.mark615.xsignin.XSignIn
version: 1.0
description: Login Plugin
author: Mark615

commands:
  xlogin:
    description: Xlogin command
    usage: /xsignin
    aliases: [xsign, xs]
    default: op
permissions: