name: xSignIn
main: de.mark615.xsignin.XSignIn
version: 1.0.4
description: Login Plugin
author: Mark615

commands:
  xlogin:
    description: xSignin command
    usage: /xsignin
    aliases: [xs, xl, xsignin]
    default: op
  xagb:
    description: xAGB command
    usage: /xagb
    aliases: [agb]
    default: op
  xmaintenance:
    description: maintenance command
    usage: /xmaintenance
    aliases: [xmt, mt, maintenance]
    default: op
permissions: